CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

DEEPFAKE_TOKEN_INDEX=-300
DEFAULT_DEEPFAKE_TOKEN = "<deepfake>"
DEFAULT_DEEPFAKE_PATCH_TOKEN = "<deepfake_patch>"
DEFAULT_DEEPFAKE_START_TOKEN="<deepfake_start>"
DEFAULT_DEEPFAKE_END_TOKEN="<deepfake_end>"